-- =====================================================================
-- 10_reference_user.sql · 조직 참조 + 유저 라이프사이클
-- =====================================================================

-- 지역 ---------------------------------------------------------------
-- 구 스키마는 accounts_school.address 가 varchar(100) 한 덩어리라
-- 시/군 단위 집계가 불가능했다. 시도·시군구를 정규화한다.
CREATE TABLE region (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sido        varchar(20) NOT NULL,
    sigungu     varchar(30) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_region UNIQUE (sido, sigungu)
);

-- 학교 ---------------------------------------------------------------
-- 구 스키마에는 학교 이름 컬럼이 아예 없었다. 마스킹된 이름을 저장한다.
-- neis_school_code 는 NEIS 공개 API 연동 키.
--
-- ⚠️ **이 컬럼 하나로는 API 를 부를 수 없다.** 급식·시간표·학사일정 API 는
--    시도교육청코드 + 표준학교코드를 **한 쌍**으로 요구한다. 짝이 되는
--    neis_office_code 를 마이그레이션 001 이 붙인다 — 아래 정의에는 없다.
--    지역명으로 유추하면 안 된다. 소재지와 관할 교육청이 다른 학교가 있고,
--    틀린 값으로 부르면 오류가 아니라 **조용히 빈 결과**가 온다.
--
-- ⚠️ info_school_id 도 마이그레이션 002 가 붙인다. 실제 학교가 아닌 조직
--    (클로즈드 테스트의 "코드잇 DA 14기")이 다른 학교의 급식·학사일정을
--    빌려 쓰게 하는 자리다. 부를 때는 coalesce(info_school_id, id) 를 쓴다.
CREATE TABLE school (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_masked       varchar(50)  NOT NULL,
    region_id         bigint       NOT NULL REFERENCES region(id),
    school_type       school_type  NOT NULL,
    neis_school_code  varchar(20)  UNIQUE,
    student_count     int          NOT NULL DEFAULT 0,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_school_region ON school(region_id);

-- 학급 ---------------------------------------------------------------
-- label: 화면에 보여줄 이름을 직접 지정하고 싶을 때만 채운다.
--        비어 있으면 앱이 "N학년 M반"으로 조립한다.
--        일반 학교는 비워두고, "1팀"처럼 학년·반 체계가 아닌 조직에만 쓴다.
CREATE TABLE grade_class (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   bigint   NOT NULL REFERENCES school(id),
    grade       smallint NOT NULL CHECK (grade BETWEEN 1 AND 6),
    class_num   smallint NOT NULL CHECK (class_num BETWEEN 1 AND 30),
    label       varchar(20),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_grade_class UNIQUE (school_id, grade, class_num)
);

-- 유저 ---------------------------------------------------------------
-- "user" 는 Postgres 예약어라 app_user 로 명명한다.
--
-- ★ 개인정보를 받지 않는다.
--   이메일·전화번호·실명·비밀번호 컬럼이 없다. 이건 누락이 아니라 설계다.
--   유저가 입력하는 것은 nickname 과 소속(class_id) 둘뿐이다.
--
-- auth_user_id : Supabase 익명 계정(auth.users)의 uuid.
--                이메일·비번 없이 접속만으로 발급된다.
--                합성 유저는 NULL이므로 실유저/합성 구분에도 쓰인다.
-- nickname     : 유저가 직접 정하는 별명. 실명이 아니다.
-- invite_code  : 친구 추가의 유일한 수단. 이 코드를 주고받아 관계를 맺는다.
--                전화번호·이메일을 받지 않으므로 서로를 찾을 다른 방법이 없다.
-- heart_balance: 구 스키마에서 point/heart 로 이원화돼 보이던 것을 하나로 통합.
-- service_unlocked_at: 친구 5명 게이트를 넘긴 시점. 온보딩 퍼널 측정용.
-- last_active_at: 구 스키마에 로그인 기록이 없어 리텐션을 친구요청으로
--                 추정해야 했던 문제를 해소.
-- is_admin     : 운영자 표시. 원래는 admin_user 테이블이 따로 있었으나,
--                운영 화면을 만들 계획이 없어 플래그 하나로 접었다.
--                운영 행위의 주체(질문 검수·신고 처리)는 여전히 남는다 —
--                그 FK 들이 이제 이 테이블을 가리킨다.
--                ★ 이 값을 바꾸는 경로는 앱에 없다. DB 에서 직접 켠다.
CREATE TABLE app_user (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id         uuid UNIQUE,
    nickname             varchar(20) NOT NULL,
    invite_code          varchar(8)  NOT NULL UNIQUE,
    gender               gender_type,
    class_id             bigint      NOT NULL REFERENCES grade_class(id),
    heart_balance        bigint      NOT NULL DEFAULT 0 CHECK (heart_balance >= 0),
    friend_count         int         NOT NULL DEFAULT 0 CHECK (friend_count >= 0),
    service_unlocked_at  timestamptz,
    status               user_status NOT NULL DEFAULT 'ACTIVE',
    is_synthetic         boolean     NOT NULL DEFAULT false,
    is_admin             boolean     NOT NULL DEFAULT false,
    last_active_at       timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    -- 헷갈리는 글자(0/O, 1/I)를 뺀 대문자·숫자 조합
    CONSTRAINT ck_invite_code CHECK (invite_code ~ '^[A-HJ-NP-Z2-9]{6,8}$')
);
CREATE INDEX idx_user_class      ON app_user(class_id);
CREATE INDEX idx_user_created    ON app_user(created_at);
CREATE INDEX idx_user_synthetic  ON app_user(is_synthetic);

-- 세션 ---------------------------------------------------------------
-- 리텐션을 추정이 아니라 실측하기 위한 테이블.
CREATE TABLE user_session (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint        NOT NULL REFERENCES app_user(id),
    platform    platform_type NOT NULL,
    app_version varchar(20)   NOT NULL,
    device_id   varchar(64),
    started_at  timestamptz   NOT NULL,
    ended_at    timestamptz,
    CONSTRAINT ck_session_order CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE INDEX idx_session_user    ON user_session(user_id);
CREATE INDEX idx_session_started ON user_session(started_at);

-- 탈퇴 사유 마스터 -----------------------------------------------------
CREATE TABLE withdrawal_reason (
    code       varchar(30) PRIMARY KEY,
    label      varchar(60) NOT NULL,
    sort_order smallint    NOT NULL DEFAULT 0,
    is_active  boolean     NOT NULL DEFAULT true
);

-- 탈퇴 기록 -----------------------------------------------------------
-- 구 스키마 최대 결함의 해소 지점.
-- accounts_userwithdraw 는 70,764건(가입자의 10.5%)이었지만 유저 식별자가 없어
-- 이탈 원인 분석이 원천 불가능했다. user_id 를 NOT NULL 로 두고
-- 자유 서술까지 받아 "기타 57%" 블랙박스를 연다.
CREATE TABLE user_withdrawal (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint      NOT NULL UNIQUE REFERENCES app_user(id),
    reason_code  varchar(30) NOT NULL REFERENCES withdrawal_reason(code),
    reason_text  varchar(500),
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_withdrawal_reason  ON user_withdrawal(reason_code);
CREATE INDEX idx_withdrawal_created ON user_withdrawal(created_at);
