-- =====================================================================
-- 20_social.sql · 친구 관계 / 연락처 / 차단
-- =====================================================================
-- 구 스키마는 친구 관계를 accounts_user.friend_id_list 라는 longtext JSON
-- 배열로 들고 있어 SQL로 펼칠 수 없었다. 정규 테이블로 대체한다.
-- =====================================================================

-- 친구 요청 -----------------------------------------------------------
CREATE TABLE friend_request (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    bigint            NOT NULL REFERENCES app_user(id),
    receiver_id  bigint            NOT NULL REFERENCES app_user(id),
    status       friend_req_status NOT NULL DEFAULT 'PENDING',
    source       relation_source   NOT NULL,
    created_at   timestamptz       NOT NULL DEFAULT now(),
    responded_at timestamptz,
    CONSTRAINT uq_friend_request UNIQUE (sender_id, receiver_id),
    CONSTRAINT ck_no_self_request CHECK (sender_id <> receiver_id)
);
CREATE INDEX idx_freq_receiver ON friend_request(receiver_id, status);
CREATE INDEX idx_freq_sender   ON friend_request(sender_id, status);

-- 친구 관계(수락된 무방향 간선) -----------------------------------------
-- user_low_id < user_high_id 를 강제해 (A,B)와 (B,A)가 중복 저장되는 것을 막는다.
CREATE TABLE friendship (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id   bigint          NOT NULL REFERENCES app_user(id),
    user_high_id  bigint          NOT NULL REFERENCES app_user(id),
    source        relation_source NOT NULL,
    created_at    timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT uq_friendship UNIQUE (user_low_id, user_high_id),
    CONSTRAINT ck_friendship_order CHECK (user_low_id < user_high_id)
);
CREATE INDEX idx_friendship_low  ON friendship(user_low_id);
CREATE INDEX idx_friendship_high ON friendship(user_high_id);

-- ⚠️ user_contact(연락처 동기화)는 MVP에서 생성하지 않는다.
--    전화번호 해시를 보관해야 하는데 개인정보를 받지 않기로 했다.
--    설계는 70_deferred_v2.sql 에 남겨두었고, MVP 적용 대상이 아니다.

-- 친구 추천 -----------------------------------------------------------
-- MVP에서는 SAME_CLASS / SAME_SCHOOL / MUTUAL_FRIEND 만 사용한다.
-- MUTUAL_CONTACT 는 연락처를 받아야 하므로 v2로 미룬다.
-- dismissed_at 으로 "안 볼래" 처리도 추적한다.
CREATE TABLE friend_recommendation (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint           NOT NULL REFERENCES app_user(id),
    recommended_user_id bigint           NOT NULL REFERENCES app_user(id),
    reason              recommend_reason NOT NULL,
    score               numeric(5,4)     NOT NULL DEFAULT 0,
    created_at          timestamptz      NOT NULL DEFAULT now(),
    dismissed_at        timestamptz,
    CONSTRAINT uq_recommendation UNIQUE (user_id, recommended_user_id),
    CONSTRAINT ck_no_self_recommend CHECK (user_id <> recommended_user_id)
);
CREATE INDEX idx_recommend_user ON friend_recommendation(user_id, dismissed_at);

-- 차단 ---------------------------------------------------------------
CREATE TABLE block_record (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint       NOT NULL REFERENCES app_user(id),
    blocked_user_id bigint       NOT NULL REFERENCES app_user(id),
    reason          block_reason NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_block UNIQUE (user_id, blocked_user_id),
    CONSTRAINT ck_no_self_block CHECK (user_id <> blocked_user_id)
);
CREATE INDEX idx_block_blocked ON block_record(blocked_user_id);
