-- =====================================================================
-- 20_social.sql · 친구 관계 / 연락처 / 차단
-- =====================================================================
-- 구 스키마는 친구 관계를 accounts_user.friend_id_list 라는 longtext JSON
-- 배열로 들고 있어 SQL로 펼칠 수 없었다. 정규 테이블로 대체한다.
-- =====================================================================

-- 친구 요청 -----------------------------------------------------------
CREATE TABLE friend_request (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    bigint            NOT NULL REFERENCES app_user(id),
    receiver_id  bigint            NOT NULL REFERENCES app_user(id),
    status       friend_req_status NOT NULL DEFAULT 'PENDING',
    source       relation_source   NOT NULL,
    created_at   timestamptz       NOT NULL DEFAULT now(),
    responded_at timestamptz,
    CONSTRAINT uq_friend_request UNIQUE (sender_id, receiver_id),
    CONSTRAINT ck_no_self_request CHECK (sender_id <> receiver_id)
);
CREATE INDEX idx_freq_receiver ON friend_request(receiver_id, status);
CREATE INDEX idx_freq_sender   ON friend_request(sender_id, status);

-- 친구 관계(수락된 무방향 간선) -----------------------------------------
-- user_low_id < user_high_id 를 강제해 (A,B)와 (B,A)가 중복 저장되는 것을 막는다.
CREATE TABLE friendship (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id   bigint          NOT NULL REFERENCES app_user(id),
    user_high_id  bigint          NOT NULL REFERENCES app_user(id),
    source        relation_source NOT NULL,
    created_at    timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT uq_friendship UNIQUE (user_low_id, user_high_id),
    CONSTRAINT ck_friendship_order CHECK (user_low_id < user_high_id)
);
CREATE INDEX idx_friendship_low  ON friendship(user_low_id);
CREATE INDEX idx_friendship_high ON friendship(user_high_id);

-- 연락처 동기화 --------------------------------------------------------
-- 전화번호 원문은 저장하지 않는다. 해시만 보관한다.
-- 웹 서비스에서는 연락처 접근이 불가하므로 v1에서는 사실상 미사용이며,
-- 향후 네이티브 앱을 붙일 때를 위한 구조다.
CREATE TABLE user_contact (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            bigint      NOT NULL REFERENCES app_user(id),
    contact_phone_hash char(64)    NOT NULL,
    matched_user_id    bigint      REFERENCES app_user(id),
    synced_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_contact UNIQUE (user_id, contact_phone_hash)
);
CREATE INDEX idx_contact_hash    ON user_contact(contact_phone_hash);
CREATE INDEX idx_contact_matched ON user_contact(matched_user_id);

-- 친구 추천 -----------------------------------------------------------
-- 서로 연락처를 갖고 있으면 MUTUAL_CONTACT 로 생성된다.
-- dismissed_at 으로 "안 볼래" 처리도 추적한다.
CREATE TABLE friend_recommendation (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint           NOT NULL REFERENCES app_user(id),
    recommended_user_id bigint           NOT NULL REFERENCES app_user(id),
    reason              recommend_reason NOT NULL,
    score               numeric(5,4)     NOT NULL DEFAULT 0,
    created_at          timestamptz      NOT NULL DEFAULT now(),
    dismissed_at        timestamptz,
    CONSTRAINT uq_recommendation UNIQUE (user_id, recommended_user_id),
    CONSTRAINT ck_no_self_recommend CHECK (user_id <> recommended_user_id)
);
CREATE INDEX idx_recommend_user ON friend_recommendation(user_id, dismissed_at);

-- 차단 ---------------------------------------------------------------
CREATE TABLE block_record (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint       NOT NULL REFERENCES app_user(id),
    blocked_user_id bigint       NOT NULL REFERENCES app_user(id),
    reason          block_reason NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_block UNIQUE (user_id, blocked_user_id),
    CONSTRAINT ck_no_self_block CHECK (user_id <> blocked_user_id)
);
CREATE INDEX idx_block_blocked ON block_record(blocked_user_id);
