-- =====================================================================
-- 30_question_vote.sql · 질문 / 투표 / 광고
-- =====================================================================

-- 질문 카테고리 --------------------------------------------------------
-- 구 스키마에는 카테고리가 없어 "외모/신체 질문이 신고 상위 5개를 독점"한다는
-- 사실을 사후 수동 분류로만 확인할 수 있었다.
-- is_sensitive 로 위험 카테고리를 사전에 표시한다.
CREATE TABLE question_category (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         varchar(30) NOT NULL UNIQUE,
    name         varchar(40) NOT NULL,
    is_sensitive boolean     NOT NULL DEFAULT false,
    sort_order   smallint    NOT NULL DEFAULT 0,
    is_active    boolean     NOT NULL DEFAULT true
);

-- 질문 요청(유저 제안 → 검수) -------------------------------------------
CREATE TABLE question_request (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               bigint         NOT NULL REFERENCES app_user(id),
    text                  varchar(200)   NOT NULL,
    proposed_scope        question_scope NOT NULL,
    proposed_category_id  bigint         REFERENCES question_category(id),
    status                request_status NOT NULL DEFAULT 'PENDING',
    reject_reason         varchar(200),
    reviewed_by_admin_id  bigint         REFERENCES app_user(id),
    reviewed_at           timestamptz,
    published_question_id bigint,          -- FK는 question 생성 후 아래에서 추가
    created_at            timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT ck_review_complete CHECK (
        (status = 'PENDING'  AND reviewed_at IS NULL)
     OR (status <> 'PENDING' AND reviewed_at IS NOT NULL)
    )
);
CREATE INDEX idx_qrequest_status ON question_request(status);
CREATE INDEX idx_qrequest_user   ON question_request(user_id);

-- 질문 ---------------------------------------------------------------
-- scope: CLASS / SCHOOL / GLOBAL. 세 스코프 모두 "친구" 안에서의 범위이며,
--        GLOBAL 도 전체 가입자가 아니라 학교 무관 친구 전체를 뜻한다.
CREATE TABLE question (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text                varchar(200)    NOT NULL,
    scope               question_scope  NOT NULL,
    category_id         bigint          NOT NULL REFERENCES question_category(id),
    status              question_status NOT NULL DEFAULT 'ACTIVE',
    source              question_source NOT NULL DEFAULT 'OFFICIAL',
    report_count        int             NOT NULL DEFAULT 0,
    created_by_admin_id bigint          REFERENCES app_user(id),
    created_at          timestamptz     NOT NULL DEFAULT now()
);
CREATE INDEX idx_question_pool ON question(status, scope, category_id);

-- 승인된 요청 → 실제 질문 연결 (단방향)
ALTER TABLE question_request
    ADD CONSTRAINT fk_qrequest_published
    FOREIGN KEY (published_question_id) REFERENCES question(id);
CREATE UNIQUE INDEX uq_qrequest_published
    ON question_request(published_question_id)
    WHERE published_question_id IS NOT NULL;

-- 투표 세션 -----------------------------------------------------------
CREATE TABLE vote_session (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint         NOT NULL REFERENCES app_user(id),
    status       session_status NOT NULL DEFAULT 'IN_PROGRESS',
    item_count   smallint       NOT NULL,
    started_at   timestamptz    NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT ck_session_complete CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
     OR (status <> 'COMPLETED')
    )
);
CREATE INDEX idx_vsession_user ON vote_session(user_id, started_at);

-- 투표 아이템(출제된 질문 1건) ------------------------------------------
-- 스킵 컬럼이 없다. 스킵 기능을 폐지했기 때문이다.
-- candidate_scope 는 출제 시점의 스코프 스냅샷이다. 질문의 scope 가 나중에
-- 바뀌어도 과거 투표의 해석이 흔들리지 않도록 복사해 둔다.
--
-- ⚠️ padded_count 를 마이그레이션 003 이 붙인다 — 아래 정의에는 없다.
--    후보가 4명이 안 될 때 스코프를 낮추지 않고 **친구 중 다른 사람으로
--    채우기** 때문에, CLASS 질문에 타반 후보가 섞일 수 있다. 그 수를 남긴 값이다.
--    ⚠️ 분석에서 이 값을 안 보면 규칙 위반과 구분되지 않는다.
CREATE TABLE vote_item (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      bigint         NOT NULL REFERENCES vote_session(id),
    user_id         bigint         NOT NULL REFERENCES app_user(id),
    question_id     bigint         NOT NULL REFERENCES question(id),
    candidate_scope question_scope NOT NULL,
    position        smallint       NOT NULL,
    shuffle_count   smallint       NOT NULL DEFAULT 0 CHECK (shuffle_count BETWEEN 0 AND 1),
    served_at       timestamptz    NOT NULL DEFAULT now(),
    voted_at        timestamptz,
    CONSTRAINT uq_vote_item_position UNIQUE (session_id, position)
);
CREATE INDEX idx_vitem_user     ON vote_item(user_id, served_at);
CREATE INDEX idx_vitem_question ON vote_item(question_id);

-- 후보 (아이템당 4명) ---------------------------------------------------
-- 구 스키마는 세트↔피스 관계를 JSON 배열로만 들고 있었다. 행으로 저장한다.
-- shuffle_round: 0 = 최초 후보, 1 = 셔플 후 후보. 둘 다 보존해
--                "어떤 후보였을 때 셔플했는가"를 분석할 수 있게 한다.
-- is_chosen: 선택된 후보 표시. 아이템당 1명만 true (부분 유니크 인덱스로 강제).
CREATE TABLE vote_candidate (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_item_id      bigint   NOT NULL REFERENCES vote_item(id),
    candidate_user_id bigint   NOT NULL REFERENCES app_user(id),
    shuffle_round     smallint NOT NULL DEFAULT 0 CHECK (shuffle_round BETWEEN 0 AND 1),
    slot              smallint NOT NULL CHECK (slot BETWEEN 1 AND 4),
    is_chosen         boolean  NOT NULL DEFAULT false,
    CONSTRAINT uq_vcandidate UNIQUE (vote_item_id, shuffle_round, slot)
);
CREATE UNIQUE INDEX uq_vcandidate_chosen
    ON vote_candidate(vote_item_id) WHERE is_chosen;
CREATE INDEX idx_vcandidate_user ON vote_candidate(candidate_user_id);

-- 광고 시청 -----------------------------------------------------------
CREATE TABLE ad_impression (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL REFERENCES app_user(id),
    placement    ad_placement NOT NULL,
    ad_network   varchar(30)  NOT NULL,
    ad_unit_id   varchar(60)  NOT NULL,
    status       ad_status    NOT NULL DEFAULT 'STARTED',
    started_at   timestamptz  NOT NULL DEFAULT now(),
    completed_at timestamptz
);
CREATE INDEX idx_ad_user      ON ad_impression(user_id, started_at);
CREATE INDEX idx_ad_placement ON ad_impression(placement, status);

-- 셔플 ---------------------------------------------------------------
-- vote_item_id 에 UNIQUE → DB 차원에서 1회 제한을 강제한다.
-- ad_impression_id 가 NOT NULL → 광고 없이 셔플한 기록은 존재할 수 없다.
CREATE TABLE vote_shuffle (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_item_id     bigint      NOT NULL UNIQUE REFERENCES vote_item(id),
    ad_impression_id bigint      NOT NULL UNIQUE REFERENCES ad_impression(id),
    created_at       timestamptz NOT NULL DEFAULT now()
);

-- 지목받은 기록(수신자 관점) --------------------------------------------
-- ⚠️ 아래 정의에 없는 컬럼이 마이그레이션으로 셋 붙었다:
--      reply_text · replied_at   008. 나를 뽑은 사람에게 보내는 1회성 답장
--                                (20하트·30자). answer_status = PRIVATE 로 표시된다
--      updated_at                004. 증분 적재 워터마크. **이 표에 특히 중요하다** —
--                                reveal_status 는 힌트를 살 때마다 바뀌는데
--                                created_at 으로 증분을 뜨면 그 변경이
--                                BigQuery 에 영영 도달하지 않는다
--
--    반대로 hint_char_index 는 **찾지 말 것.** 006 이 여기 넣었다가 007 이
--    hint_purchase.char_index 로 옮겼다. 자모 힌트마다 다른 글자를 가리키게
--    바뀌었기 때문이다.
CREATE TABLE vote_received (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_item_id  bigint        NOT NULL UNIQUE REFERENCES vote_item(id),
    voter_id      bigint        NOT NULL REFERENCES app_user(id),
    receiver_id   bigint        NOT NULL REFERENCES app_user(id),
    question_id   bigint        NOT NULL REFERENCES question(id),
    is_read       boolean       NOT NULL DEFAULT false,
    read_at       timestamptz,
    reveal_status reveal_status NOT NULL DEFAULT 'HIDDEN',
    answer_status answer_status NOT NULL DEFAULT 'NONE',
    answered_at   timestamptz,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT ck_no_self_vote CHECK (voter_id <> receiver_id),
    CONSTRAINT ck_read_flag CHECK ((is_read AND read_at IS NOT NULL) OR (NOT is_read AND read_at IS NULL))
);
CREATE INDEX idx_vreceived_receiver ON vote_received(receiver_id, created_at);
CREATE INDEX idx_vreceived_status   ON vote_received(answer_status, reveal_status);

-- 힌트 구매 -----------------------------------------------------------
-- ⚠️ **아래 정의는 최초 설계이고, W14(마이그레이션 006·007)가 갈아치웠다.**
--    이 파일만 읽으면 죽은 요금제를 현행으로 오해한다. 현행은 이렇다:
--
--      기본 5종 (GENDER·INITIAL·MEDIAL·FINAL·CLASS) · 각 20하트 · 순서 없음
--      FULL_NAME  이름 공개 · 100하트 · 기본 5종 중 3개 이상을 연 뒤에만
--      GENDER 는 광고로도 열 수 있다(하루 1회) → heart_cost = 0 인 행이 생긴다
--
--    값이 흩어지면 어긋나므로 요금은 db/rls/hints.sql 의 hint_cost() 하나가
--    정한다. 해금 기준은 같은 파일의 hint_unlock_min().
--
--    무엇이 바뀌었나 — 아래 컬럼 정의를 그대로 읽으면 안 되는 이유:
--      step        누진 단계(1~4)가 아니라 **몇 번째로 열었나**(1~6)로 뜻이 바뀌었다
--      heart_cost  > 0 이 아니라 >= 0 이다 (광고로 연 힌트가 0)
--      uq_hint_step  (vote_received_id, step) → uq_hint_kind (vote_received_id, hint_type)
--                    순서가 자유로워졌으니 "같은 단계 두 번"이 아니라
--                    **같은 유형 두 번**을 막아야 한다
--      char_index  007 이 붙인다. 자모 힌트가 가리키는 글자 위치이며,
--                  006 과 달리 **힌트 한 건마다 따로** 뽑는다
--      ad_impression_id  006 이 붙인다. 광고로 열었으면 그 광고, 하트로 샀으면 NULL
--
--    ⚠️ 분석에서 매출·소비를 셀 때 heart_cost = 0 행(광고 무료 힌트)을 거를 것.
--       정합성 검사 4번이 이걸 전제로 고쳐져 있다.
--
--    구 서비스의 누진 요금(200 → 300 → 500 → 1000)은 **벤치마크로도 쓰지 않는다.**
--    단가가 10배 달라 하트 경제 전체가 다른 체제다 — 생성기가 투표 적립을
--    실측 5~15 에서 2~7 로 낮춘 것도 같은 이유다(synthetic-v2.yaml).
--
-- 하트 차감은 heart_transaction 이 이 행을 참조하는 단방향 구조.
CREATE TABLE hint_purchase (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_received_id bigint      NOT NULL REFERENCES vote_received(id),
    user_id          bigint      NOT NULL REFERENCES app_user(id),
    hint_type        hint_type   NOT NULL,
    step             smallint    NOT NULL CHECK (step BETWEEN 1 AND 4),
    heart_cost       int         NOT NULL CHECK (heart_cost > 0),
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_hint_step UNIQUE (vote_received_id, step)
);
CREATE INDEX idx_hint_user ON hint_purchase(user_id, created_at);
