-- =====================================================================
-- 40_heart_report.sql · 하트 경제 / 신고 · 제재
-- =====================================================================

-- 거래 유형 마스터 -----------------------------------------------------
-- 구 스키마는 delta_point 값만 보고 의미를 역추론해야 했다
-- (5~15 = 투표 적립, -300 = 힌트 구매 ... 전부 추측이었다).
CREATE TABLE heart_transaction_type (
    code      varchar(30) PRIMARY KEY,
    label     varchar(50) NOT NULL,
    is_credit boolean     NOT NULL,
    is_active boolean     NOT NULL DEFAULT true
);

-- 충전 상품 -----------------------------------------------------------
-- 구 스키마는 productId 문자열만 있고 가격·수량이 코드에만 있어
-- 매출 계산 시 값을 하드코딩해야 했다.
CREATE TABLE heart_product (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code varchar(40) NOT NULL UNIQUE,
    heart_amount int         NOT NULL CHECK (heart_amount > 0),
    price_krw    int         NOT NULL CHECK (price_krw > 0),
    label        varchar(30),
    is_active    boolean     NOT NULL DEFAULT true
);

-- 충전 결제 -----------------------------------------------------------
-- 성공/실패를 한 테이블에 status 로 통합한다.
-- 구 스키마는 별도 테이블이었고 실패 로깅이 2023-09에 조용히 끊겨
-- 그 이후로는 실패율 자체를 계산할 수 없었다.
CREATE TABLE heart_purchase (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              bigint          NOT NULL REFERENCES app_user(id),
    product_id           bigint          NOT NULL REFERENCES heart_product(id),
    platform             platform_type   NOT NULL,
    store_transaction_id varchar(120)    UNIQUE,
    status               purchase_status NOT NULL DEFAULT 'PENDING',
    failure_reason       varchar(120),
    price_krw            int             NOT NULL,
    heart_amount         int             NOT NULL,
    created_at           timestamptz     NOT NULL DEFAULT now(),
    completed_at         timestamptz
);
CREATE INDEX idx_purchase_user   ON heart_purchase(user_id, created_at);
CREATE INDEX idx_purchase_status ON heart_purchase(status, created_at);

-- 하트 원장 -----------------------------------------------------------
-- 이 프로젝트에서 가장 중요한 테이블.
--
-- 구 스키마의 원장은 순합계가 201만인데 유저 잔액 총합은 20억이었다.
-- 가입 지급과 충전이 원장에 남지 않았기 때문이다(heart.777이 57,873건
-- 팔렸는데 원장의 +777 행은 21건뿐이었다). 잔액을 원장으로 재구성하는 것이
-- 불가능했고, 누락을 탐지할 방법조차 없었다.
--
-- 규칙: 모든 하트 증감은 예외 없이 이 테이블을 거친다.
-- balance_after 로 거래 직후 잔액을 남겨 app_user.heart_balance 와
-- 대조하면 정합성이 즉시 검증된다.
--
-- source_* 컬럼은 이 거래의 원인을 가리키는 단방향 참조다.
-- 유형에 따라 하나만 채워지며, 나머지는 NULL이다.
CREATE TABLE heart_transaction (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          bigint      NOT NULL REFERENCES app_user(id),
    type_code        varchar(30) NOT NULL REFERENCES heart_transaction_type(code),
    delta            int         NOT NULL CHECK (delta <> 0),
    balance_after    bigint      NOT NULL CHECK (balance_after >= 0),
    vote_item_id     bigint      REFERENCES vote_item(id),
    hint_purchase_id bigint      REFERENCES hint_purchase(id),
    purchase_id      bigint      REFERENCES heart_purchase(id),
    ad_impression_id bigint      REFERENCES ad_impression(id),
    admin_id         bigint      REFERENCES app_user(id),
    memo             varchar(200),
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_htx_user    ON heart_transaction(user_id, created_at);
CREATE INDEX idx_htx_type    ON heart_transaction(type_code, created_at);
CREATE INDEX idx_htx_created ON heart_transaction(created_at);

-- 소비처는 한 번만 정산되어야 한다
CREATE UNIQUE INDEX uq_htx_hint     ON heart_transaction(hint_purchase_id) WHERE hint_purchase_id IS NOT NULL;
CREATE UNIQUE INDEX uq_htx_purchase ON heart_transaction(purchase_id)      WHERE purchase_id      IS NOT NULL;
CREATE UNIQUE INDEX uq_htx_ad       ON heart_transaction(ad_impression_id) WHERE ad_impression_id IS NOT NULL;


-- =====================================================================
-- 신고 · 제재
-- =====================================================================

CREATE TABLE report_reason (
    code        varchar(30)   PRIMARY KEY,
    label       varchar(60)   NOT NULL,
    target_type report_target NOT NULL,
    is_active   boolean       NOT NULL DEFAULT true
);

-- 자동 제재 정책 -------------------------------------------------------
-- 임계값을 코드가 아니라 데이터로 정의한다.
-- 구 시스템은 피신고 10회 이상 116명 중 제재된 사람이 0명이었고,
-- 253회 신고받은 유저도 정상 상태로 활동 중이었다.
-- 정책이 스키마에 드러나야 감사가 가능하다.
CREATE TABLE sanction_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(60)   NOT NULL,
    target_type     report_target NOT NULL,
    threshold_count int           NOT NULL CHECK (threshold_count > 0),
    window_days     smallint      NOT NULL CHECK (window_days > 0),
    action_type     sanction_type NOT NULL,
    action_days     smallint,
    is_active       boolean       NOT NULL DEFAULT true
);

-- 신고 ---------------------------------------------------------------
-- 유저·질문·게시글·댓글 신고를 한 테이블로 통합하되,
-- 대상별 FK를 명시 컬럼으로 두어 참조 무결성을 지킨다.
-- (다형 참조 방식은 FK를 걸 수 없어 채택하지 않았다.)
-- post / post_comment 참조는 90_board.sql 에서 추가한다.
CREATE TABLE report (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id          bigint        NOT NULL REFERENCES app_user(id),
    target_type          report_target NOT NULL,
    target_user_id       bigint        REFERENCES app_user(id),
    target_question_id   bigint        REFERENCES question(id),
    target_post_id       bigint,
    target_comment_id    bigint,
    reason_code          varchar(30)   NOT NULL REFERENCES report_reason(code),
    detail_text          varchar(500),
    status               report_status NOT NULL DEFAULT 'PENDING',
    reviewed_by_admin_id bigint        REFERENCES app_user(id),
    reviewed_at          timestamptz,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    -- target_type 과 실제로 채워진 대상 컬럼이 일치해야 한다
    CONSTRAINT ck_report_target CHECK (
        (target_type = 'USER'     AND target_user_id     IS NOT NULL)
     OR (target_type = 'QUESTION' AND target_question_id IS NOT NULL)
     OR (target_type = 'POST'     AND target_post_id     IS NOT NULL)
     OR (target_type = 'COMMENT'  AND target_comment_id  IS NOT NULL)
    )
);
CREATE INDEX idx_report_status ON report(status, created_at);
CREATE INDEX idx_report_target ON report(target_type, target_user_id);

-- 제재 ---------------------------------------------------------------
-- triggered_by_report_id 로 근거 신고를 명시한다.
-- 이 연결이 구 시스템에는 아예 없었다.
CREATE TABLE sanction (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               bigint        NOT NULL REFERENCES app_user(id),
    type                  sanction_type NOT NULL,
    triggered_by_report_id bigint       REFERENCES report(id),
    policy_id             bigint        REFERENCES sanction_policy(id),
    issued_by_admin_id    bigint        REFERENCES app_user(id),
    reason                varchar(200)  NOT NULL,
    starts_at             timestamptz   NOT NULL DEFAULT now(),
    ends_at               timestamptz,
    is_active             boolean       NOT NULL DEFAULT true,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT ck_sanction_period CHECK (ends_at IS NULL OR ends_at > starts_at)
);
CREATE INDEX idx_sanction_user   ON sanction(user_id, is_active);
CREATE INDEX idx_sanction_active ON sanction(is_active, ends_at);
