-- =====================================================================
-- 50_school_service.sql · 공지 / 급식 / 시간표 / 학사일정
-- =====================================================================
-- 네 영역 모두 NEIS 공개 API 연동과 수동 입력을 함께 지원한다.
-- source        : 이 행이 어디서 왔는가
-- external_id   : 외부 원본 식별자 (재동기화 시 매칭 키)
-- is_manually_overridden : 사람이 손댄 행. 재동기화가 덮어쓰지 않도록 보호한다.
-- =====================================================================

-- 공지사항 -----------------------------------------------------------
CREATE TABLE school_notice (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id              bigint      NOT NULL REFERENCES school(id),
    title                  varchar(200) NOT NULL,
    body                   text         NOT NULL,
    source                 data_source  NOT NULL DEFAULT 'MANUAL',
    external_id            varchar(80),
    is_manually_overridden boolean      NOT NULL DEFAULT false,
    created_by_admin_id    bigint       REFERENCES app_user(id),
    published_at           timestamptz  NOT NULL DEFAULT now(),
    created_at             timestamptz  NOT NULL DEFAULT now(),
    updated_at             timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_notice_school ON school_notice(school_id, published_at DESC);
CREATE UNIQUE INDEX uq_notice_external
    ON school_notice(school_id, external_id) WHERE external_id IS NOT NULL;

-- 공지 열람 기록 -------------------------------------------------------
-- 어떤 공지가 실제로 읽히는지 측정해 알림 정책을 조정한다.
CREATE TABLE school_notice_read (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id bigint      NOT NULL REFERENCES school_notice(id),
    user_id   bigint      NOT NULL REFERENCES app_user(id),
    read_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_notice_read UNIQUE (notice_id, user_id)
);
CREATE INDEX idx_notice_read_user ON school_notice_read(user_id);

-- 급식표 -------------------------------------------------------------
-- 학교·날짜·끼니에 UNIQUE. 같은 날 중복 급식이 들어오는 것을 DB가 막는다.
CREATE TABLE meal_plan (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id              bigint       NOT NULL REFERENCES school(id),
    serve_date             date         NOT NULL,
    meal_type              meal_type    NOT NULL,
    calorie_kcal           numeric(6,1),
    source                 data_source  NOT NULL DEFAULT 'NEIS',
    external_id            varchar(80),
    is_manually_overridden boolean      NOT NULL DEFAULT false,
    synced_at              timestamptz,
    created_at             timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_meal_plan UNIQUE (school_id, serve_date, meal_type)
);
CREATE INDEX idx_meal_date ON meal_plan(serve_date);

-- 급식 메뉴 항목 -------------------------------------------------------
-- 메뉴를 한 덩어리 텍스트가 아니라 요리 단위로 분리한다.
-- "인기 급식 메뉴" 분석과 알레르기 필터가 가능해진다.
CREATE TABLE meal_menu_item (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id  bigint      NOT NULL REFERENCES meal_plan(id) ON DELETE CASCADE,
    dish_name     varchar(80) NOT NULL,
    allergy_codes varchar(60),
    sort_order    smallint    NOT NULL DEFAULT 0
);
CREATE INDEX idx_menu_item_plan ON meal_menu_item(meal_plan_id);
CREATE INDEX idx_menu_item_dish ON meal_menu_item(dish_name);

-- 시간표 -------------------------------------------------------------
-- 학급·학기·요일·교시에 UNIQUE → 한 칸에 두 과목이 들어갈 수 없다.
-- 교사명은 마스킹해서 저장한다.
CREATE TABLE timetable (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id               bigint      NOT NULL REFERENCES grade_class(id),
    semester               varchar(10) NOT NULL,
    day_of_week            smallint    NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    period                 smallint    NOT NULL CHECK (period BETWEEN 1 AND 12),
    subject_name           varchar(40) NOT NULL,
    teacher_name_masked    varchar(20),
    room                   varchar(30),
    source                 data_source NOT NULL DEFAULT 'NEIS',
    is_manually_overridden boolean     NOT NULL DEFAULT false,
    synced_at              timestamptz,
    CONSTRAINT uq_timetable UNIQUE (class_id, semester, day_of_week, period)
);
CREATE INDEX idx_timetable_class ON timetable(class_id, semester);

-- 학사일정 -----------------------------------------------------------
-- 시작·종료일을 분리해 기간 일정을 지원한다.
-- grade_scope 가 NULL 이면 전교 대상, 값이 있으면 해당 학년만 해당한다.
CREATE TABLE school_event (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id              bigint            NOT NULL REFERENCES school(id),
    title                  varchar(120)      NOT NULL,
    event_type             school_event_type NOT NULL,
    start_date             date              NOT NULL,
    end_date               date              NOT NULL,
    is_all_day             boolean           NOT NULL DEFAULT true,
    grade_scope            smallint,
    source                 data_source       NOT NULL DEFAULT 'NEIS',
    external_id            varchar(80),
    is_manually_overridden boolean           NOT NULL DEFAULT false,
    synced_at              timestamptz,
    CONSTRAINT ck_event_period CHECK (end_date >= start_date)
);
CREATE INDEX idx_event_school ON school_event(school_id, start_date);
CREATE UNIQUE INDEX uq_event_external
    ON school_event(school_id, external_id) WHERE external_id IS NOT NULL;

-- 외부 동기화 이력은 두지 않는다 ----------------------------------------
-- external_sync_log 라는 표가 여기 있었다(migration 010 에서 삭제).
-- "언제 무엇을 성공/실패했는지" 를 남기려던 것인데, **넣는 코드를 한 번도
-- 붙이지 않았다.** 수집기 셋(neis_schools/meals/events) 어느 것도 쓰지 않았고
-- 반년 가까이 0행이었다.
--
-- 지운 이유는 안 써서가 아니라, 빈 표가 ERD 에 남아 있으면 **동기화 이력이
-- 남고 있다고 읽히기 때문**이다. 없는 편이 정직하다.
--
-- 지금은 수집을 손으로 돌리고 결과를 눈으로 본다. 이걸 DAG 로 돌려 사람이
-- 안 보게 되는 날 다시 필요해진다 — 그때는 **넣는 코드와 같이** 만든다.
