-- =====================================================================
-- 60_board.sql · 학교별 익명 게시판
-- =====================================================================
-- ⚠️ v1 서비스에서는 개통하지 않는다.
--    익명 게시판은 신고 검토 인력이 필수인데 1인 프로젝트로는 감당할 수 없다.
--    스키마만 미리 설계해두고, 모니터링 체계가 갖춰지면 연다.
--    (자세한 근거는 DECISIONS.md 참조)
--
-- 익명성 설계:
--   화면에는 익명으로 표시하되 author_id 는 내부에 남긴다.
--   신고·제재가 불가능한 완전 익명은 사고 시 대응할 방법이 없기 때문이다.
-- =====================================================================

CREATE TABLE board_category (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(20) NOT NULL UNIQUE,
    name        varchar(30) NOT NULL,
    description varchar(100),
    sort_order  smallint    NOT NULL DEFAULT 0,
    is_active   boolean     NOT NULL DEFAULT true
);

-- 게시글 -------------------------------------------------------------
CREATE TABLE post (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     bigint         NOT NULL REFERENCES school(id),
    category_id   bigint         NOT NULL REFERENCES board_category(id),
    author_id     bigint         NOT NULL REFERENCES app_user(id),
    title         varchar(120)   NOT NULL,
    body          text           NOT NULL,
    view_count    int            NOT NULL DEFAULT 0,
    like_count    int            NOT NULL DEFAULT 0,
    comment_count int            NOT NULL DEFAULT 0,
    report_count  int            NOT NULL DEFAULT 0,
    status        content_status NOT NULL DEFAULT 'PUBLISHED',
    created_at    timestamptz    NOT NULL DEFAULT now(),
    updated_at    timestamptz    NOT NULL DEFAULT now()
);
-- 학교별 게시판이므로 목록 조회는 항상 school_id + category_id 로 걸린다
CREATE INDEX idx_post_board  ON post(school_id, category_id, created_at DESC);
CREATE INDEX idx_post_author ON post(author_id);
CREATE INDEX idx_post_status ON post(status);

-- 댓글 ---------------------------------------------------------------
-- anonymous_seq: 글 안에서만 유효한 익명 번호(익명1, 익명2 ...).
--   같은 사람은 같은 글에서 같은 번호를 유지해 대화 맥락이 읽히게 한다.
--   글이 다르면 번호도 달라져 글 사이의 동일인 추적은 불가능하다.
CREATE TABLE post_comment (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           bigint         NOT NULL REFERENCES post(id),
    parent_comment_id bigint         REFERENCES post_comment(id),
    author_id         bigint         NOT NULL REFERENCES app_user(id),
    anonymous_seq     smallint       NOT NULL CHECK (anonymous_seq > 0),
    body              varchar(1000)  NOT NULL,
    like_count        int            NOT NULL DEFAULT 0,
    status            content_status NOT NULL DEFAULT 'PUBLISHED',
    created_at        timestamptz    NOT NULL DEFAULT now(),
    updated_at        timestamptz    NOT NULL DEFAULT now(),
    -- 한 글에서 한 사람은 하나의 익명 번호만 갖는다
    CONSTRAINT uq_comment_anon UNIQUE (post_id, author_id, anonymous_seq)
);
CREATE INDEX idx_comment_post   ON post_comment(post_id, created_at);
CREATE INDEX idx_comment_parent ON post_comment(parent_comment_id);
CREATE INDEX idx_comment_author ON post_comment(author_id);

-- 좋아요 -------------------------------------------------------------
CREATE TABLE post_like (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL REFERENCES post(id),
    user_id    bigint      NOT NULL REFERENCES app_user(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_like UNIQUE (post_id, user_id)
);
CREATE INDEX idx_post_like_user ON post_like(user_id);

CREATE TABLE comment_like (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint      NOT NULL REFERENCES post_comment(id),
    user_id    bigint      NOT NULL REFERENCES app_user(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_comment_like UNIQUE (comment_id, user_id)
);
CREATE INDEX idx_comment_like_user ON comment_like(user_id);

-- 신고 테이블의 게시판 대상 FK ------------------------------------------
-- report 는 40_heart_report.sql 에서 먼저 생성되므로 여기서 FK를 붙인다.
ALTER TABLE report
    ADD CONSTRAINT fk_report_post    FOREIGN KEY (target_post_id)    REFERENCES post(id),
    ADD CONSTRAINT fk_report_comment FOREIGN KEY (target_comment_id) REFERENCES post_comment(id);
