-- =====================================================================
-- 60_board.sql · 학교별 게시판
-- =====================================================================
-- ⚠️ **아래 정의는 익명 게시판 전제로 쓰였고, W9 가 전제를 바꿨다.**
--    이 파일만 읽으면 "게시판은 안 열렸다"고 오해한다. 현황은 이렇다:
--
--      게시판은 **열려 있다**. 단 익명이 아니라 **닉네임이 드러나는
--      자유게시판**이다(W9). 학교 단위이고 신고 경로가 함께 있다.
--      익명 게시판은 **폐기가 아니라 보류**다 — 재검토 조건은 [[DECISIONS]].
--
--    왜 닉네임이면 열 수 있었나:
--      익명을 미룬 이유는 "사고가 나도 책임을 물을 수 없다"는 것이었다.
--      글쓴이가 드러나면 그 전제 자체가 바뀐다. 신고 검토 인력이 없다는
--      사정은 그대로지만, 이름이 붙는 글은 스스로 억제가 걸린다.
--
--    남의 닉네임을 띄우려고 app_user 정책을 넓히지 않았다 —
--    board_post 뷰로만 노출한다(db/rls/board.sql).
--
-- 익명성 설계(보류된 쪽의 원안):
--   화면에는 익명으로 표시하되 author_id 는 내부에 남긴다.
--   신고·제재가 불가능한 완전 익명은 사고 시 대응할 방법이 없기 때문이다.
-- =====================================================================

CREATE TABLE board_category (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(20) NOT NULL UNIQUE,
    name        varchar(30) NOT NULL,
    description varchar(100),
    sort_order  smallint    NOT NULL DEFAULT 0,
    is_active   boolean     NOT NULL DEFAULT true
);

-- 게시글 -------------------------------------------------------------
CREATE TABLE post (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     bigint         NOT NULL REFERENCES school(id),
    category_id   bigint         NOT NULL REFERENCES board_category(id),
    author_id     bigint         NOT NULL REFERENCES app_user(id),
    title         varchar(120)   NOT NULL,
    body          text           NOT NULL,
    view_count    int            NOT NULL DEFAULT 0,
    like_count    int            NOT NULL DEFAULT 0,
    comment_count int            NOT NULL DEFAULT 0,
    report_count  int            NOT NULL DEFAULT 0,
    status        content_status NOT NULL DEFAULT 'PUBLISHED',
    created_at    timestamptz    NOT NULL DEFAULT now(),
    updated_at    timestamptz    NOT NULL DEFAULT now()
);
-- 학교별 게시판이므로 목록 조회는 항상 school_id + category_id 로 걸린다
CREATE INDEX idx_post_board  ON post(school_id, category_id, created_at DESC);
CREATE INDEX idx_post_author ON post(author_id);
CREATE INDEX idx_post_status ON post(status);

-- 댓글 ---------------------------------------------------------------
-- ⚠️ **anonymous_seq 는 마이그레이션 005 가 nullable 로 바꿨고, 지금은 안 쓴다.**
--    닉네임 게시판이라 익명 번호를 채울 사람이 없다. 아래 NOT NULL 을
--    그대로 읽지 말 것.
--
--    왜 컬럼을 지우지 않았나 — 익명 게시판은 보류이지 폐기가 아니다.
--    지웠다 다시 만들면 그 사이 댓글에는 번호를 소급할 수 없다.
--
--    ⚠️ 아래 uq_comment_anon 도 005 가 걷어낸다. 그대로 두면
--    **한 사람이 한 글에 댓글을 두 번 달 수 없다** — 대화가 성립하지 않는다.
--
-- anonymous_seq(익명으로 열 때의 원안): 글 안에서만 유효한 익명 번호(익명1, 익명2 ...).
--   같은 사람은 같은 글에서 같은 번호를 유지해 대화 맥락이 읽히게 한다.
--   글이 다르면 번호도 달라져 글 사이의 동일인 추적은 불가능하다.
CREATE TABLE post_comment (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           bigint         NOT NULL REFERENCES post(id),
    parent_comment_id bigint         REFERENCES post_comment(id),
    author_id         bigint         NOT NULL REFERENCES app_user(id),
    anonymous_seq     smallint       NOT NULL CHECK (anonymous_seq > 0),
    body              varchar(1000)  NOT NULL,
    like_count        int            NOT NULL DEFAULT 0,
    status            content_status NOT NULL DEFAULT 'PUBLISHED',
    created_at        timestamptz    NOT NULL DEFAULT now(),
    updated_at        timestamptz    NOT NULL DEFAULT now(),
    -- 한 글에서 한 사람은 하나의 익명 번호만 갖는다
    CONSTRAINT uq_comment_anon UNIQUE (post_id, author_id, anonymous_seq)
);
CREATE INDEX idx_comment_post   ON post_comment(post_id, created_at);
CREATE INDEX idx_comment_parent ON post_comment(parent_comment_id);
CREATE INDEX idx_comment_author ON post_comment(author_id);

-- 좋아요 -------------------------------------------------------------
CREATE TABLE post_like (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL REFERENCES post(id),
    user_id    bigint      NOT NULL REFERENCES app_user(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_like UNIQUE (post_id, user_id)
);
CREATE INDEX idx_post_like_user ON post_like(user_id);

CREATE TABLE comment_like (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint      NOT NULL REFERENCES post_comment(id),
    user_id    bigint      NOT NULL REFERENCES app_user(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_comment_like UNIQUE (comment_id, user_id)
);
CREATE INDEX idx_comment_like_user ON comment_like(user_id);

-- 신고 테이블의 게시판 대상 FK ------------------------------------------
-- report 는 40_heart_report.sql 에서 먼저 생성되므로 여기서 FK를 붙인다.
ALTER TABLE report
    ADD CONSTRAINT fk_report_post    FOREIGN KEY (target_post_id)    REFERENCES post(id),
    ADD CONSTRAINT fk_report_comment FOREIGN KEY (target_comment_id) REFERENCES post_comment(id);
