-- =====================================================================
-- 70_deferred_v2.sql · v2로 미룬 테이블
-- =====================================================================
-- ⚠️ MVP 적용 대상이 아니다. README 의 스키마 생성 명령에서 제외돼 있다.
--
-- 왜 여기 있나:
--   설계는 끝났지만 MVP에서 만들면 안 되는 것들을 지운 대신 보관한다.
--   지워버리면 나중에 다시 설계해야 하고, MVP DDL에 넣으면
--   "쓰지도 않는데 개인정보를 담을 수 있는 테이블"이 존재하게 된다.
--
-- 적용 시점:
--   네이티브 앱을 붙여 연락처 접근이 가능해지고,
--   전화번호 수집에 대한 동의 절차를 갖춘 뒤.
-- =====================================================================

-- 연락처 동기화 --------------------------------------------------------
-- 전화번호 원문은 저장하지 않고 해시만 보관하는 설계다.
-- 그래도 해시는 원문 대조가 가능하므로(같은 번호 → 같은 해시)
-- 개인정보로 취급해야 한다. 그래서 MVP에서 만들지 않는다.
CREATE TABLE user_contact (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            bigint      NOT NULL REFERENCES app_user(id),
    contact_phone_hash char(64)    NOT NULL,
    matched_user_id    bigint      REFERENCES app_user(id),
    synced_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_contact UNIQUE (user_id, contact_phone_hash)
);
CREATE INDEX idx_contact_hash    ON user_contact(contact_phone_hash);
CREATE INDEX idx_contact_matched ON user_contact(matched_user_id);
