-- =====================================================================
-- 95_resync_sequences.sql · identity 시퀀스 재동기화
-- =====================================================================
-- ⚠️ 대량 적재 후 반드시 실행할 것.
--
-- 왜 필요한가:
--   컬럼을 GENERATED BY DEFAULT AS IDENTITY 로 선언했기 때문에
--   INSERT 시 id 를 직접 지정할 수 있다(합성 데이터 적재에 필요).
--   그런데 명시적으로 넣은 값은 **시퀀스를 전진시키지 않는다.**
--
--   합성 유저를 id 1~5000 으로 적재한 뒤 실유저가 가입하면
--   DB는 id=1 을 발급하려 하고 PK 충돌로 회원가입이 실패한다.
--
--   실제로 재현됨:
--     INSERT INTO region (id, ...) VALUES (1, ...);   -- 명시 삽입
--     INSERT INTO region (sido, sigungu) VALUES (...); -- 자동 발급
--     → ERROR: duplicate key value violates unique constraint "region_pkey"
--
-- 무엇을 하는가:
--   모든 identity 컬럼의 시퀀스를 현재 최대값 다음으로 맞춘다.
--   테이블이 비어 있으면 1로 초기화한다.
--
-- 실행 시점:
--   - 합성 데이터 적재 직후
--   - 백업 복원 직후
--   - id 를 직접 지정하는 어떤 대량 작업 뒤에도
-- =====================================================================

DO $$
DECLARE
    r        record;
    max_id   bigint;
    seq_name text;
BEGIN
    FOR r IN
        SELECT c.table_name, c.column_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE c.table_schema = 'public'
          AND c.is_identity  = 'YES'
          AND t.table_type   = 'BASE TABLE'
    LOOP
        seq_name := pg_get_serial_sequence('public.' || quote_ident(r.table_name), r.column_name);
        IF seq_name IS NULL THEN
            CONTINUE;
        END IF;

        EXECUTE format('SELECT COALESCE(max(%I), 0) FROM %I', r.column_name, r.table_name)
            INTO max_id;

        IF max_id = 0 THEN
            -- 빈 테이블: 다음 발급이 1이 되도록
            EXECUTE format('SELECT setval(%L, 1, false)', seq_name);
        ELSE
            -- 다음 발급이 max_id + 1 이 되도록
            EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
        END IF;

        RAISE NOTICE '% .% → 시퀀스를 %(으)로 맞춤', r.table_name, r.column_name, max_id;
    END LOOP;
END $$;
